import { useEffect, useMemo, useState } from "react"
import { Link } from "react-router-dom"
import {
  Calendar,
  FilePlus2,
  Link2,
  Plus,
  Receipt,
  Search,
  Sparkles,
  X,
  ArrowUpRight,
  Wallet,
  CheckCircle2,
  TrendingUp,
} from "lucide-react"
import type { InvoiceListItem } from "../types/operations"
import { fetchInvoicesList } from "../services/operations"
import { Card } from "../components/ui/Card"
import { StatusBadge } from "../components/ui/Badge"
import { SkeletonTable } from "../components/ui/Skeleton"
import { INVOICE_STATUS_META } from "../lib/status"
import { formatINR, formatDateTime, initials } from "../lib/format"

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<InvoiceListItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [status, setStatus] = useState<string>("all")
  const [copiedId, setCopiedId] = useState<string | null>(null)

  // Search + date-range filters. Kept separate from the table so the toolbar
  // stays mounted even when there is no data — the layout never jumps.
  const [query, setQuery] = useState("")
  const [dateFrom, setDateFrom] = useState<string>("")
  const [dateTo, setDateTo] = useState<string>("")

  // Creation modal visibility.
  const [showCreate, setShowCreate] = useState(false)

  useEffect(() => {
    let cancelled = false
    fetchInvoicesList()
      .then((data) => {
        if (!cancelled) setInvoices(data)
      })
      .catch((err) => {
        if (!cancelled)
          setError(err instanceof Error ? err.message : "Failed to load invoices")
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  // Combine status tabs, search query and date range into one filtered list.
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return invoices
      .filter((i) => (status === "all" ? true : i.status === status))
      .filter((i) => {
        if (dateFrom && Date.parse(i.created_at ?? "0") < Date.parse(dateFrom)) return false
        if (dateTo && Date.parse(i.created_at ?? "0") > Date.parse(`${dateTo}T23:59:59`)) return false
        return true
      })
      .filter((i) => {
        if (!q) return true
        const haystack = [
          i.invoice_number,
          i.customer_name,
          i.customer_email,
          i.description,
        ]
          .filter(Boolean)
          .join(" ")
          .toLowerCase()
        return haystack.includes(q)
      })
      .slice()
      .sort((a, b) => Date.parse(b.created_at ?? "0") - Date.parse(a.created_at ?? "0"))
  }, [invoices, status, query, dateFrom, dateTo])

  const statusTabs = useMemo(() => {
    const counts: Record<string, number> = { all: invoices.length }
    for (const i of invoices) counts[i.status] = (counts[i.status] ?? 0) + 1
    return [
      { key: "all", label: "All", count: counts.all ?? 0 },
      { key: "ISSUED", label: "Issued", count: counts.ISSUED ?? 0 },
      { key: "PAID", label: "Paid", count: counts.PAID ?? 0 },
      { key: "EXPIRED", label: "Expired", count: counts.EXPIRED ?? 0 },
      { key: "CANCELLED", label: "Cancelled", count: counts.CANCELLED ?? 0 },
    ]
  }, [invoices])

  // --- Metric mini-cards over the old packed subtitle string ---
  const totalRevenue = invoices.reduce((s, i) => s + i.amount, 0)
  const totalPaid = invoices.filter((i) => i.status === "PAID").reduce((s, i) => s + i.amount, 0)
  const totalOutstanding = totalRevenue - totalPaid

  const metrics = [
    {
      label: "Total Revenue",
      value: formatINR(totalRevenue),
      icon: Wallet,
      accent: "text-slate-100",
      iconBox: "bg-slate-700/40 text-slate-300",
    },
    {
      label: "Paid",
      value: formatINR(totalPaid),
      icon: CheckCircle2,
      accent: "text-accent",
      iconBox: "bg-accent-soft text-accent",
    },
    {
      label: "Outstanding",
      value: formatINR(totalOutstanding),
      icon: TrendingUp,
      accent: "text-royal",
      iconBox: "bg-royal-soft text-royal",
    },
  ]

  async function copyLink(invoice: InvoiceListItem) {
    const link = `${window.location.origin}/api/invoices/access/${invoice.secure_token}`
    try {
      await navigator.clipboard.writeText(link)
      setCopiedId(invoice.id)
      setTimeout(() => setCopiedId(null), 2000)
    } catch {
      window.prompt("Copy the invoice link:", link)
    }
  }

  const hasFilters = Boolean(query || dateFrom || dateTo || status !== "all")

  return (
    <div className="space-y-6">
      {/* Header row: title + primary CTA */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-100">Invoices</h1>
          <p className="mt-1 text-sm text-slate-500">
            Payment links customers open to complete recovery — generated by webhooks or sent by your agents.
          </p>
        </div>
        <button
          onClick={() => setShowCreate(true)}
          className="inline-flex items-center gap-2 rounded-lg bg-royal px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-royal/80"
        >
          <Plus className="h-4 w-4" />
          New Invoice
        </button>
      </div>

      {/* Metric mini-cards — Total Revenue / Paid / Outstanding */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {metrics.map((m) => (
          <div
            key={m.label}
            className="flex items-center gap-3 rounded-xl border border-edge bg-panel p-4"
          >
            <span className={`flex h-9 w-9 items-center justify-center rounded-lg ${m.iconBox}`}>
              <m.icon className="h-4 w-4" />
            </span>
            <div className="min-w-0">
              <p className="text-xs text-slate-500">{m.label}</p>
              <p className={`truncate text-lg font-bold ${m.accent}`}>{m.value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Search + date-range toolbar (always mounted so the layout is stable) */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search invoices by ID, customer name…"
            className="w-full rounded-lg border border-edge bg-panel-2 py-2 pl-9 pr-3 text-sm text-slate-200 placeholder:text-slate-500 transition-colors focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/40"
          />
        </div>
        <div className="flex items-center gap-2">
          <Calendar className="h-4 w-4 text-slate-500" />
          <input
            type="date"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
            className="rounded-lg border border-edge bg-panel-2 px-3 py-2 text-xs text-slate-300 transition-colors focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/40"
          />
          <span className="text-xs text-slate-600">to</span>
          <input
            type="date"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
            className="rounded-lg border border-edge bg-panel-2 px-3 py-2 text-xs text-slate-300 transition-colors focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/40"
          />
          {hasFilters && (
            <button
              onClick={() => {
                setQuery("")
                setDateFrom("")
                setDateTo("")
                setStatus("all")
              }}
              className="rounded-lg border border-edge bg-panel px-3 py-2 text-xs text-slate-400 transition-colors hover:text-slate-200"
            >
              Clear
            </button>
          )}
        </div>
      </div>

      {/* Status pill tabs */}
      <div className="flex flex-wrap gap-1.5">
        {statusTabs.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setStatus(tab.key)}
            className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
              status === tab.key
                ? "border-indigo-500/40 bg-indigo-600/15 text-indigo-300"
                : "border-edge bg-panel text-slate-400 hover:text-slate-300"
            }`}
          >
            {tab.label} <span className="ml-1 opacity-70">{tab.count}</span>
          </button>
        ))}
      </div>

      <Card className="overflow-hidden">
        {loading ? (
          <div className="p-6">
            <SkeletonTable rows={7} />
          </div>
        ) : error ? (
          <div className="p-6 text-center text-red-400">{error}</div>
        ) : filtered.length === 0 ? (
          /* Empty state — modern dark-glass card with a single, human message */
          <div className="p-6">
            {invoices.length === 0 && !hasFilters ? (
              <EmptyInvoicesState onCreateAction={() => setShowCreate(true)} />
            ) : (
              <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-edge bg-panel-2 px-6 py-14 text-center">
                <Search className="h-8 w-8 text-slate-600" />
                <p className="mt-3 text-sm font-medium text-slate-300">No invoices match your filters</p>
                <p className="mt-1 text-xs text-slate-500">Try a different date range or search term.</p>
              </div>
            )}
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-edge text-xs uppercase tracking-wide text-slate-500">
                  <th className="px-4 py-3 font-medium">Invoice</th>
                  <th className="px-4 py-3 font-medium">Customer</th>
                  <th className="px-4 py-3 font-medium">Amount</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Issued</th>
                  <th className="px-4 py-3 font-medium">Viewed</th>
                  <th className="px-4 py-3 font-medium">Delivered</th>
                  <th className="px-4 py-3 text-right font-medium">Action</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((inv) => {
                  const meta = INVOICE_STATUS_META[inv.status] ?? {
                    label: inv.status,
                    badge: "bg-slate-700/40 text-slate-300 border-slate-600/40",
                    dot: "bg-slate-400",
                    text: "text-slate-300",
                  }
                  return (
                    <tr
                      key={inv.id}
                      className="border-b border-edge/50 transition-colors last:border-0 hover:bg-panel-2"
                    >
                      <td className="px-4 py-3">
                        <span className="font-mono text-xs font-medium text-slate-300">
                          {inv.invoice_number}
                        </span>
                        {inv.description && (
                          <span className="block max-w-[180px] truncate text-xs text-slate-500">
                            {inv.description}
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2.5">
                          <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-slate-700 text-[10px] font-bold text-slate-200">
                            {initials(inv.customer_name)}
                          </span>
                          <div className="min-w-0">
                            <div className="truncate font-medium text-slate-200">
                              {inv.customer_name || "Unknown customer"}
                            </div>
                            {inv.customer_email && (
                              <div className="truncate text-xs text-slate-500">
                                {inv.customer_email}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-3 font-semibold text-slate-200">
                        {formatINR(inv.amount)}
                      </td>
                      <td className="px-4 py-3">
                        <StatusBadge meta={meta} />
                      </td>
                      <td className="px-4 py-3 text-slate-500">
                        {formatDateTime(inv.issued_at ?? inv.created_at)}
                      </td>
                      <td className="px-4 py-3 text-slate-500">
                        {inv.viewed_at ? (
                          <>
                            {formatDateTime(inv.viewed_at)}
                            {inv.access_count > 1 && (
                              <span className="ml-1 text-xs text-slate-600">
                                ×{inv.access_count}
                              </span>
                            )}
                          </>
                        ) : (
                          "Not yet"
                        )}
                      </td>
                      <td className="px-4 py-3 text-slate-500">
                        {inv.delivered_via ? (
                          <>
                            <span className="capitalize">{inv.delivered_via}</span>
                            {inv.delivered_at && (
                              <span className="block text-xs text-slate-600">
                                {formatDateTime(inv.delivered_at)}
                              </span>
                            )}
                          </>
                        ) : (
                          "—"
                        )}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <div className="flex items-center justify-end gap-2">
                          {inv.case_id && (
                            <Link
                              to={`/case/${inv.case_id}`}
                              className="text-xs font-medium text-indigo-400 hover:text-indigo-300"
                            >
                              Case
                            </Link>
                          )}
                          <button
                            onClick={() => copyLink(inv)}
                            className="rounded-lg bg-slate-800 px-2.5 py-1.5 text-xs font-medium text-slate-200 transition-colors hover:bg-slate-700"
                          >
                            {copiedId === inv.id ? "Copied!" : "Copy link"}
                          </button>
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {/* Create invoice drawer/modal */}
      {showCreate && (
        <CreateInvoiceModal onClose={() => setShowCreate(false)} />
      )}
    </div>
  )
}

/**
 * Modern empty-state card.
 * - Lucide `Receipt` icon in a dark-glass circular badge with subtle border/glow.
 * - Punchy copy on how invoices get created (webhooks / manual links).
 * - Two actions: create a payment link, or spin up a sample invoice.
 */
function EmptyInvoicesState({ onCreateAction }: { onCreateAction: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-edge bg-panel-2 px-6 py-16 text-center">
      <div className="flex h-16 w-16 items-center justify-center rounded-full border border-edge bg-panel">
        <Receipt className="h-8 w-8 text-royal" />
      </div>

      <h3 className="mt-5 text-lg font-semibold text-slate-200">
        No recovery invoices yet
      </h3>
      <p className="mt-2 max-w-md text-sm leading-relaxed text-slate-500">
        Invoices are created the moment a payment fails — from your gateway
        webhook — or when you send a customer a manual payment link. Once a
        customer opens theirs, you'll see it here.
      </p>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row">
        <button
          onClick={onCreateAction}
          className="inline-flex items-center justify-center gap-2 rounded-lg bg-royal px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-royal/80"
        >
          <Link2 className="h-4 w-4" />
          Create Payment Link
        </button>
        <button className="inline-flex items-center justify-center gap-2 rounded-lg border border-edge bg-panel px-5 py-2.5 text-sm font-medium text-slate-200 transition-colors hover:bg-elevated">
          <Sparkles className="h-4 w-4 text-cyan-400" />
          Generate Sample Invoice
        </button>
      </div>

      <p className="mt-5 text-xs text-slate-600">
        Tip: trigger a test webhook from the Simulation page to populate this list instantly.
      </p>
    </div>
  )
}

/**
 * Lightweight creation drawer (right-side panel) for a "+ New Invoice".
 * In a full integration this submits to the invoices API; here it captures
 * the inputs and previews the generated payment link.
 */
function CreateInvoiceModal({ onClose }: { onClose: () => void }) {
  const [amount, setAmount] = useState("")
  const [customer, setCustomer] = useState("")

  return (      <div
        className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      >
        <div
          onClick={(e) => e.stopPropagation()}
          className="flex h-full w-full max-w-md flex-col border-l border-edge bg-canvas p-6 shadow-2xl"
        >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600/15 text-indigo-300">
              <FilePlus2 className="h-4 w-4" />
            </span>
            <h2 className="text-lg font-semibold text-slate-100">New Invoice</h2>
          </div>
        <button
          onClick={onClose}
          className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-elevated hover:text-slate-200"
        >
            <X className="h-4 w-4" />
          </button>
        </div>

        <p className="mt-2 text-sm text-slate-500">
          Create a manual payment link for a customer.
        </p>

        <div className="mt-6 space-y-4">
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-400">
              Customer
            </label>
            <input
              value={customer}
              onChange={(e) => setCustomer(e.target.value)}
              placeholder="customer@company.com"
              className="w-full rounded-lg border border-edge bg-panel-2 px-3 py-2.5 text-sm text-slate-200 placeholder:text-slate-500 focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/40"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-400">
              Amount (₹)
            </label>
            <input
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              inputMode="numeric"
              placeholder="0.00"
              className="w-full rounded-lg border border-edge bg-panel-2 px-3 py-2.5 text-sm text-slate-200 placeholder:text-slate-500 focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/40"
            />
          </div>
        </div>

        {amount ? (
          <div className="mt-5 rounded-lg border border-indigo-500/20 bg-indigo-500/10 p-4">
            <p className="text-xs text-indigo-300">Payment link preview</p>
            <p className="mt-1 truncate font-mono text-xs text-slate-300">
              {window.location.origin}/api/invoices/access/demo-{customer || "customer"}
            </p>
            <p className="mt-1 flex items-center gap-1 text-xs font-semibold text-indigo-200">
              <ArrowUpRight className="h-3 w-3" />
              {formatINR(Number(amount) * 100)}
            </p>
          </div>
        ) : (
          <div className="mt-5 rounded-lg border border-dashed border-slate-800 p-4 text-center text-xs text-slate-500">
            Add an amount to preview the payment link.
          </div>
        )}

        <div className="mt-auto pt-6">
          <button
            onClick={onClose}
            className="w-full rounded-lg bg-royal px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-royal/80"
          >
            Create Invoice
          </button>
        </div>
      </div>
    </div>
  )
}
